### ISSUE TITLE
When adding text to textarea from jQuery, line numbers not applied !

### ISSUE THREAD

**Issue by miranos** [Dorious/jquery-numberedtextarea#1]
Hi
The plugin works well when adding text with typing from keyboard.

When i add text from jQuery like this:
`$("#mytextarea").val("LONG TEXT WITH LINE BREAK TO TEST");`

Numbers not applied, any solution ?

**Comment by Dorious** [comment]
The only solution is to trigger change event.
$("#mytextarea").val("LONG TEXT WITH LINE BREAK TO TEST").trigger('change')
